"""Auto-generated UI code for image_gallery_ui.py - DO NOT EDIT MANUALLY."""

from runtime import UIWindow



class ImageGalleryUI(UIWindow):
    """Generated UI window from markdown definition."""

    _mcp_enabled = True
    _mcp_source_md = '# Image Gallery\n\n## Metadata\n\n```yaml\nformat: uimd\nformat-version: 1\nkind: window\ndescription: "Manual validation surface for the Image element, Sixel rendering, fallback rendering, and sizing modes."\ntags: [example, image]\n```\n\n## Members\n\n```yaml\nheader:\n  type: label\n  text: "Image Gallery"\n  description: "Window title."\n  expose: false\n\nclose_btn:\n  type: button\n  title: X\n  description: "Close the image gallery."\n\nfallback_label:\n  type: label\n  text: "Fallback cover"\n  description: "Fallback row label."\n\nsixel_label:\n  type: label\n  text: "Sixel contain"\n  description: "Sixel contain row label."\n\nstretch_label:\n  type: label\n  text: "Sixel stretch"\n  description: "Sixel stretch row label."\n\ncamera_fb:\n  type: image\n  source: "shared/assets/image_samples/camera.png"\n  alt: "camera fallback"\n  fit: cover\n  render_mode: fallback\n  description: "Camera image forced through fallback rendering."\n\nastro_fb:\n  type: image\n  source: "shared/assets/image_samples/astronaut.png"\n  alt: "astronaut fallback"\n  fit: cover\n  render_mode: fallback\n  description: "Astronaut image forced through fallback rendering."\n\ncoffee_fb:\n  type: image\n  source: "shared/assets/image_samples/coffee.png"\n  alt: "coffee fallback"\n  fit: cover\n  render_mode: fallback\n  description: "Coffee image forced through fallback rendering."\n\ncoins_fb:\n  type: image\n  source: "shared/assets/image_samples/coins.png"\n  alt: "coins fallback"\n  fit: cover\n  render_mode: fallback\n  description: "Coins image forced through fallback rendering."\n\ncamera_ctn:\n  type: image\n  source: "shared/assets/image_samples/camera.png"\n  alt: "camera sixel"\n  fit: contain\n  render_mode: sixel\n  description: "Camera image in forced Sixel contain mode."\n\nastro_ctn:\n  type: image\n  source: "shared/assets/image_samples/astronaut.png"\n  alt: "astronaut sixel"\n  fit: contain\n  render_mode: sixel\n  description: "Astronaut image in forced Sixel contain mode."\n\ncoffee_ctn:\n  type: image\n  source: "shared/assets/image_samples/coffee.png"\n  alt: "coffee sixel"\n  fit: contain\n  render_mode: sixel\n  description: "Coffee image in forced Sixel contain mode."\n\ncoins_ctn:\n  type: image\n  source: "shared/assets/image_samples/coins.png"\n  alt: "coins sixel"\n  fit: contain\n  render_mode: sixel\n  description: "Coins image in forced Sixel contain mode."\n\ncamera_str:\n  type: image\n  source: "shared/assets/image_samples/camera.png"\n  alt: "camera stretch"\n  fit: stretch\n  render_mode: sixel\n  description: "Camera image in forced Sixel stretch mode."\n\nastro_str:\n  type: image\n  source: "shared/assets/image_samples/astronaut.png"\n  alt: "astronaut stretch"\n  fit: stretch\n  render_mode: sixel\n  description: "Astronaut image in forced Sixel stretch mode."\n\ncoffee_str:\n  type: image\n  source: "shared/assets/image_samples/coffee.png"\n  alt: "coffee stretch"\n  fit: stretch\n  render_mode: sixel\n  description: "Coffee image in forced Sixel stretch mode."\n\ncoins_str:\n  type: image\n  source: "shared/assets/image_samples/coins.png"\n  alt: "coins stretch"\n  fit: stretch\n  render_mode: sixel\n  description: "Coins image in forced Sixel stretch mode."\n\nstatus:\n  type: label\n  text: "Rows: fallback cover, forced Sixel contain, forced Sixel stretch."\n  description: "Current image validation status."\n```\n\n## Style\n\n```yaml\ninclude: dark\nthis:\n  border-width: 0\n@header:\n  text-align: center\n  background: "#18324f"\n  color: "#ffffff"\n@close_btn:\n  background: "#7f1d1d"\n  focus-background: "#dc2626"\n  color: "#ffffff"\n@fallback_label:\n  color: "#93c5fd"\n@sixel_label:\n  color: "#93c5fd"\n@stretch_label:\n  color: "#93c5fd"\nimage:\n  background: transparent\n  color: "#d1d5db"\n@status:\n  color: "#93c5fd"\n```\n\n## User Interface\n\n```ui\n+--------------------------------------------------------------------------------------+\n| header.................................................................. close_btn.. |\n|                                                                                      |\n| fallback_label...................................................................... |\n|  camera_fb........... astro_fb............ coffee_fb........... coins_fb............. |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|                                                                                      |\n| sixel_label......................................................................... |\n|  camera_ctn.......... astro_ctn........... coffee_ctn.......... coins_ctn........... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|                                                                                      |\n| stretch_label....................................................................... |\n|  camera_str.......... astro_str........... coffee_str.......... coins_str........... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|  .................... .................... .................... .................... |\n|                                                                                      |\n| status.............................................................................. |\n+--------------------------------------------------------------------------------------+\n```\n'
    _mcp_agent_metadata = {'window': {'description': 'Manual validation surface for the Image element, Sixel rendering, fallback rendering, and sizing modes.'}, 'elements': {'header': {'role': 'text', 'description': 'Window title.', 'expose': False}, 'close_btn': {'role': 'action', 'description': 'Close the image gallery.', 'expose': True}, 'fallback_label': {'role': 'text', 'description': 'Fallback row label.', 'expose': True}, 'sixel_label': {'role': 'text', 'description': 'Sixel contain row label.', 'expose': True}, 'stretch_label': {'role': 'text', 'description': 'Sixel stretch row label.', 'expose': True}, 'camera_fb': {'role': 'text', 'description': 'Camera image forced through fallback rendering.', 'expose': True}, 'astro_fb': {'role': 'text', 'description': 'Astronaut image forced through fallback rendering.', 'expose': True}, 'coffee_fb': {'role': 'text', 'description': 'Coffee image forced through fallback rendering.', 'expose': True}, 'coins_fb': {'role': 'text', 'description': 'Coins image forced through fallback rendering.', 'expose': True}, 'camera_ctn': {'role': 'text', 'description': 'Camera image in forced Sixel contain mode.', 'expose': True}, 'astro_ctn': {'role': 'text', 'description': 'Astronaut image in forced Sixel contain mode.', 'expose': True}, 'coffee_ctn': {'role': 'text', 'description': 'Coffee image in forced Sixel contain mode.', 'expose': True}, 'coins_ctn': {'role': 'text', 'description': 'Coins image in forced Sixel contain mode.', 'expose': True}, 'camera_str': {'role': 'text', 'description': 'Camera image in forced Sixel stretch mode.', 'expose': True}, 'astro_str': {'role': 'text', 'description': 'Astronaut image in forced Sixel stretch mode.', 'expose': True}, 'coffee_str': {'role': 'text', 'description': 'Coffee image in forced Sixel stretch mode.', 'expose': True}, 'coins_str': {'role': 'text', 'description': 'Coins image in forced Sixel stretch mode.', 'expose': True}, 'status': {'role': 'text', 'description': 'Current image validation status.', 'expose': True}}}
    _mcp_app_tools = {}

    def __init__(self):
        super().__init__(
            title="Image Gallery",
            layout=COMPILED_LAYOUT,
            members=COMPILED_MEMBERS,
            style=COMPILED_STYLE
        )

        self.astro_ctn = self.create_element("astro_ctn", "image", source='shared/assets/image_samples/astronaut.png', alt='astronaut sixel', fit='contain', render_mode='sixel')
        self.astro_fb = self.create_element("astro_fb", "image", source='shared/assets/image_samples/astronaut.png', alt='astronaut fallback', fit='cover', render_mode='fallback')
        self.astro_str = self.create_element("astro_str", "image", source='shared/assets/image_samples/astronaut.png', alt='astronaut stretch', fit='stretch', render_mode='sixel')
        self.camera_ctn = self.create_element("camera_ctn", "image", source='shared/assets/image_samples/camera.png', alt='camera sixel', fit='contain', render_mode='sixel')
        self.camera_fb = self.create_element("camera_fb", "image", source='shared/assets/image_samples/camera.png', alt='camera fallback', fit='cover', render_mode='fallback')
        self.camera_str = self.create_element("camera_str", "image", source='shared/assets/image_samples/camera.png', alt='camera stretch', fit='stretch', render_mode='sixel')
        self.close_btn = self.create_element("close_btn", "button", title='X')
        self.coffee_ctn = self.create_element("coffee_ctn", "image", source='shared/assets/image_samples/coffee.png', alt='coffee sixel', fit='contain', render_mode='sixel')
        self.coffee_fb = self.create_element("coffee_fb", "image", source='shared/assets/image_samples/coffee.png', alt='coffee fallback', fit='cover', render_mode='fallback')
        self.coffee_str = self.create_element("coffee_str", "image", source='shared/assets/image_samples/coffee.png', alt='coffee stretch', fit='stretch', render_mode='sixel')
        self.coins_ctn = self.create_element("coins_ctn", "image", source='shared/assets/image_samples/coins.png', alt='coins sixel', fit='contain', render_mode='sixel')
        self.coins_fb = self.create_element("coins_fb", "image", source='shared/assets/image_samples/coins.png', alt='coins fallback', fit='cover', render_mode='fallback')
        self.coins_str = self.create_element("coins_str", "image", source='shared/assets/image_samples/coins.png', alt='coins stretch', fit='stretch', render_mode='sixel')
        self.fallback_label = self.create_element("fallback_label", "label", text='Fallback cover')
        self.header = self.create_element("header", "label", text='Image Gallery')
        self.sixel_label = self.create_element("sixel_label", "label", text='Sixel contain')
        self.status = self.create_element("status", "label", text='Rows: fallback cover, forced Sixel contain, forced Sixel stretch.')
        self.stretch_label = self.create_element("stretch_label", "label", text='Sixel stretch')
    def on_close_btn_click(self):
        pass


    def _dispatch_element_changed(self, element, value):
        if element is self.close_btn:
            self.on_close_btn_click()
        super()._dispatch_element_changed(element, value)

    def _dispatch_confirmed(self, element, value):
        pass
        super()._dispatch_confirmed(element, value)

    def _dispatch_selection_changed(self, element, value):
        pass
        super()._dispatch_selection_changed(element, value)


COMPILED_MEMBERS = {
    "header": {
        "type": 'label',
        "text": 'Image Gallery',
        "description": 'Window title.',
        "expose": False,
    },
    "close_btn": {
        "type": 'button',
        "title": 'X',
        "description": 'Close the image gallery.',
    },
    "fallback_label": {
        "type": 'label',
        "text": 'Fallback cover',
        "description": 'Fallback row label.',
    },
    "sixel_label": {
        "type": 'label',
        "text": 'Sixel contain',
        "description": 'Sixel contain row label.',
    },
    "stretch_label": {
        "type": 'label',
        "text": 'Sixel stretch',
        "description": 'Sixel stretch row label.',
    },
    "camera_fb": {
        "type": 'image',
        "source": 'shared/assets/image_samples/camera.png',
        "alt": 'camera fallback',
        "fit": 'cover',
        "render_mode": 'fallback',
        "description": 'Camera image forced through fallback rendering.',
    },
    "astro_fb": {
        "type": 'image',
        "source": 'shared/assets/image_samples/astronaut.png',
        "alt": 'astronaut fallback',
        "fit": 'cover',
        "render_mode": 'fallback',
        "description": 'Astronaut image forced through fallback rendering.',
    },
    "coffee_fb": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coffee.png',
        "alt": 'coffee fallback',
        "fit": 'cover',
        "render_mode": 'fallback',
        "description": 'Coffee image forced through fallback rendering.',
    },
    "coins_fb": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coins.png',
        "alt": 'coins fallback',
        "fit": 'cover',
        "render_mode": 'fallback',
        "description": 'Coins image forced through fallback rendering.',
    },
    "camera_ctn": {
        "type": 'image',
        "source": 'shared/assets/image_samples/camera.png',
        "alt": 'camera sixel',
        "fit": 'contain',
        "render_mode": 'sixel',
        "description": 'Camera image in forced Sixel contain mode.',
    },
    "astro_ctn": {
        "type": 'image',
        "source": 'shared/assets/image_samples/astronaut.png',
        "alt": 'astronaut sixel',
        "fit": 'contain',
        "render_mode": 'sixel',
        "description": 'Astronaut image in forced Sixel contain mode.',
    },
    "coffee_ctn": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coffee.png',
        "alt": 'coffee sixel',
        "fit": 'contain',
        "render_mode": 'sixel',
        "description": 'Coffee image in forced Sixel contain mode.',
    },
    "coins_ctn": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coins.png',
        "alt": 'coins sixel',
        "fit": 'contain',
        "render_mode": 'sixel',
        "description": 'Coins image in forced Sixel contain mode.',
    },
    "camera_str": {
        "type": 'image',
        "source": 'shared/assets/image_samples/camera.png',
        "alt": 'camera stretch',
        "fit": 'stretch',
        "render_mode": 'sixel',
        "description": 'Camera image in forced Sixel stretch mode.',
    },
    "astro_str": {
        "type": 'image',
        "source": 'shared/assets/image_samples/astronaut.png',
        "alt": 'astronaut stretch',
        "fit": 'stretch',
        "render_mode": 'sixel',
        "description": 'Astronaut image in forced Sixel stretch mode.',
    },
    "coffee_str": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coffee.png',
        "alt": 'coffee stretch',
        "fit": 'stretch',
        "render_mode": 'sixel',
        "description": 'Coffee image in forced Sixel stretch mode.',
    },
    "coins_str": {
        "type": 'image',
        "source": 'shared/assets/image_samples/coins.png',
        "alt": 'coins stretch',
        "fit": 'stretch',
        "render_mode": 'sixel',
        "description": 'Coins image in forced Sixel stretch mode.',
    },
    "status": {
        "type": 'label',
        "text": 'Rows: fallback cover, forced Sixel contain, forced Sixel stretch.',
        "description": 'Current image validation status.',
    },
}

COMPILED_STYLE = {
    "this": {
        "background": '#162033',
        "border-color": 'transparent',
        "border-width": 0,
    },
    "label": {
        "background": 'transparent',
        "color": '#cbd5e1',
        "cursor-background": '#b8d7ff',
        "cursor-color": '#000000',
    },
    "@dialog_header": {
        "text-align": 'center',
        "background": '#1d314c',
    },
    "@window_header": {
        "text-align": 'center',
        "background": '#1d314c',
    },
    "infolabel": {
        "background": 'transparent',
        "color": '#b8c4d8',
    },
    "textinput": {
        "background": '#0d1524',
        "color": '#e5e7eb',
        "focus-background": '#243a5c',
        "focus-color": '#ffffff',
        "edit-background": '#2d456d',
        "edit-color": '#ffffff',
        "cursor-background": '#ffffff',
        "cursor-color": '#0e1117',
        "selected-background": '#2563eb',
        "selected-color": '#ffffff',
    },
    "numberinput": {
        "background": '#0d1524',
        "color": '#e5e7eb',
        "focus-background": '#243a5c',
        "focus-color": '#ffffff',
        "edit-background": '#2d456d',
        "edit-color": '#ffffff',
        "cursor-background": '#ffffff',
        "cursor-color": '#0e1117',
    },
    "combobox": {
        "background": '#0d1524',
        "color": '#e5e7eb',
        "focus-background": '#243a5c',
        "focus-color": '#ffffff',
        "edit-background": '#2d456d',
        "edit-color": '#e5e7eb',
        "selected-background": '#2563eb',
        "selected-color": '#ffffff',
    },
    "listbox": {
        "background": '#0d1524',
        "color": '#cbd5e1',
        "focus-background": '#1d2f4d',
        "focus-color": '#ffffff',
        "edit-background": '#243a5c',
        "edit-color": '#cbd5e1',
        "selected-background": '#2563eb',
        "selected-color": '#ffffff',
    },
    "uielement": {
        "focus-background": '#ffffff14',
        "edit-background": '#ffffff18',
        "selected-background": '#ffffff26',
        "selected-color": '#ffffff',
    },
    "uiscrollview": {
        "focus-background": '#ffffff14',
        "edit-background": '#ffffff18',
        "selected-background": '#ffffff26',
        "selected-color": '#ffffff',
    },
    "checkbox": {
        "background": 'transparent',
        "color": '#b8c4d8',
        "focus-color": '#66aaff',
        "checked-background": 'transparent',
        "checked-color": '#44cc88',
        "unchecked-background": 'transparent',
    },
    "button": {
        "background": '#334155',
        "color": '#e2e8f0',
        "focus-background": '#2b5f9f',
        "focus-color": '#ffffff',
    },
    "@header": {
        "text-align": 'center',
        "background": '#18324f',
        "color": '#ffffff',
    },
    "@close_btn": {
        "background": '#7f1d1d',
        "focus-background": '#dc2626',
        "color": '#ffffff',
    },
    "@fallback_label": {
        "color": '#93c5fd',
    },
    "@sixel_label": {
        "color": '#93c5fd',
    },
    "@stretch_label": {
        "color": '#93c5fd',
    },
    "image": {
        "background": 'transparent',
        "color": '#d1d5db',
    },
    "@status": {
        "color": '#93c5fd',
    },
}

COMPILED_LAYOUT = [
    {
        'row': 0,
        'col': 1,
        'relative_col': 1,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 72,
        'chars_height': 1,
        'margin_right': 13,
        'margin_bottom': 38,
        'width': 72,
        'height': 1,
        'type': 'label',
        'name': 'header'
    },
    {
        'row': 0,
        'col': 74,
        'relative_col': 74,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 11,
        'chars_height': 1,
        'margin_right': 1,
        'margin_bottom': 38,
        'height': 1,
        'type': 'button',
        'name': 'close_btn'
    },
    {
        'row': 2,
        'col': 1,
        'relative_row': 2,
        'relative_col': 1,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 84,
        'chars_height': 1,
        'margin_right': 1,
        'margin_bottom': 36,
        'height': 1,
        'type': 'label',
        'name': 'fallback_label'
    },
    {
        'row': 3,
        'col': 2,
        'relative_row': 3,
        'relative_col': 2,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 64,
        'margin_bottom': 26,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'camera_fb'
    },
    {
        'row': 3,
        'col': 23,
        'relative_row': 3,
        'relative_col': 23,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 43,
        'margin_bottom': 26,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'astro_fb'
    },
    {
        'row': 3,
        'col': 44,
        'relative_row': 3,
        'relative_col': 44,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 22,
        'margin_bottom': 26,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'coffee_fb'
    },
    {
        'row': 3,
        'col': 65,
        'relative_row': 3,
        'relative_col': 65,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 21,
        'chars_height': 10,
        'margin_bottom': 26,
        'height': 10,
        'type': 'image',
        'name': 'coins_fb'
    },
    {
        'row': 14,
        'col': 1,
        'relative_row': 14,
        'relative_col': 1,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 84,
        'chars_height': 1,
        'margin_right': 1,
        'margin_bottom': 24,
        'height': 1,
        'type': 'label',
        'name': 'sixel_label'
    },
    {
        'row': 15,
        'col': 2,
        'relative_row': 15,
        'relative_col': 2,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 64,
        'margin_bottom': 14,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'camera_ctn'
    },
    {
        'row': 15,
        'col': 23,
        'relative_row': 15,
        'relative_col': 23,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 43,
        'margin_bottom': 14,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'astro_ctn'
    },
    {
        'row': 15,
        'col': 44,
        'relative_row': 15,
        'relative_col': 44,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 22,
        'margin_bottom': 14,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'coffee_ctn'
    },
    {
        'row': 15,
        'col': 65,
        'relative_row': 15,
        'relative_col': 65,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 1,
        'margin_bottom': 14,
        'height': 10,
        'type': 'image',
        'name': 'coins_ctn'
    },
    {
        'row': 26,
        'col': 1,
        'relative_row': 26,
        'relative_col': 1,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 84,
        'chars_height': 1,
        'margin_right': 1,
        'margin_bottom': 12,
        'height': 1,
        'type': 'label',
        'name': 'stretch_label'
    },
    {
        'row': 27,
        'col': 2,
        'relative_row': 27,
        'relative_col': 2,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 64,
        'margin_bottom': 2,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'camera_str'
    },
    {
        'row': 27,
        'col': 23,
        'relative_row': 27,
        'relative_col': 23,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 43,
        'margin_bottom': 2,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'astro_str'
    },
    {
        'row': 27,
        'col': 44,
        'relative_row': 27,
        'relative_col': 44,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 22,
        'margin_bottom': 2,
        'width': 20,
        'height': 10,
        'type': 'image',
        'name': 'coffee_str'
    },
    {
        'row': 27,
        'col': 65,
        'relative_row': 27,
        'relative_col': 65,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 20,
        'chars_height': 10,
        'margin_right': 1,
        'margin_bottom': 2,
        'height': 10,
        'type': 'image',
        'name': 'coins_str'
    },
    {
        'row': 38,
        'col': 1,
        'relative_row': 38,
        'relative_col': 1,
        'cell_row': 0,
        'cell_col': 0,
        'cell_chars_width': 86,
        'cell_chars_height': 39,
        'cell_width': 86,
        'cell_height': 39,
        'cell_width_mode': 'auto',
        'cell_height_mode': 'auto',
        'width_mode': 'expanded',
        'chars_width': 84,
        'chars_height': 1,
        'margin_right': 1,
        'height': 1,
        'type': 'label',
        'name': 'status'
    }
]
